<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getOutstockDiscountAmount()): ?>
    <tr>
    	<?php $partialpaymentHelper = Mage::helper('partialpayment/partialpayment'); ?>
    	<?php if(($this->getSource()->getBaseDepositAmount() > 0) && ($this->getSource()->getBaseFeeAmount() > 0) && ($this->getSource()->getSubtotalInclTax() >= $partialpaymentHelper->getMinimumOrderAmount()) && ($this->getSource()->getSubtotalInclTax() > $this->getSource()->getBaseFeeAmount()) && ($this->getSource()->getGrandTotal() > $this->getSource()->getBaseFeeAmount()) && ($this->getSource()->getBaseDepositAmount() > $this->getSource()->getTaxAmount())): ?>
	        <td class="label">
				<?php echo Mage::helper('outstockdiscount')->formatOutstockDiscount($this->getSource()->getOutstockDiscountAmount()); ?>
			</td>
    	    <td>
            	<?php echo $this->displayPrices($this->getSource()->getBaseOutstockDiscountAmount(), $this->getSource()->getOutstockDiscountAmount()); ?>
        	</td>
		<?php endif; ?>
    </tr>
<?php endif; ?>