<?php
/**
 * Product:     Custom Product Preview
 * Package:     Aitoc_Aitcg_3.0.1_1.0.0_520274
 * Purchase ID: 9XHJkpl9USQGlgqMmhzeUoZOIR22A95V3tio9yYTqY
 * Generated:   2013-03-05 20:52:02
 * File path:   app/design/frontend/default/default/template/aitcg/sharedimage/head.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<meta property="og:title" content="<?php echo $this->stripTags($productName, null, true) ?>" />
<meta property="og:description" content="<?php echo $productDescription ?>" />
<meta property="og:type" content="product" />
<meta property="og:image" content="<?php echo $sharedImgThumbnailUrl ?>" />
<meta property="og:url" content="<?php echo $currentUrl ?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName() ?>" />