<?php
/**
 * Product:     Custom Product Preview
 * Package:     Aitoc_Aitcg_3.0.1_1.0.0_520274
 * Purchase ID: 9XHJkpl9USQGlgqMmhzeUoZOIR22A95V3tio9yYTqY
 * Generated:   2013-03-05 20:52:02
 * File path:   app/design/adminhtml/default/default/template/aitcg/window/printarea.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
'<div id="message-popup-window-mask" onclick="Aitcg.editors.ed_{{option_id}}.closeEditor();"></div>'+
'<div id="message-popup-window" class="message-popup print-area-editor">'+
    '<div class="message-popup-head">'+
        '<a href="#" onclick="Aitcg.editors.ed_{{option_id}}.closeEditor(); return false;" title="<?php echo $this->__('close'); ?>"><span><?php echo $this->__('close'); ?></span></a>'+
        '<h2><?php echo Mage::helper('aitcg')->__('Edit Printable Area'); ?></h2>'+
    '</div>'+
    '<div>'+
        '<img src="{{full_image}}" id="printable-area-image" width="{{img_width}}" height="{{img_height}}" alt="" />'+
    '</div>'+
    '<div class="message-popup-head">'+
        '<a class="apply-but" href="#" onclick="Aitcg.editors.ed_{{option_id}}.applyCoords(); return false;" title="<?php echo $this->__('apply'); ?>"><?php echo $this->__('apply'); ?></a>'+
    '</div>'+
'</div>'