<?php
/**
 * Product:     Custom Product Preview
 * Package:     Aitoc_Aitcg_3.0.1_1.0.0_520274
 * Purchase ID: 9XHJkpl9USQGlgqMmhzeUoZOIR22A95V3tio9yYTqY
 * Generated:   2013-03-05 20:52:02
 * File path:   app/design/frontend/default/default/template/aitcg/image/converter/vml.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php echo '<?xml version= "1.0"?>'; ?>
<HTML xmlns:v = "urn:schemas-microsoft-com:vml" xmlns="http://www.w3.org/1999/xhtml">
    <HEAD>
        <STYLE></STYLE>
    </HEAD>
    <BODY>
        <?php echo $this->getVmlElements(); ?>
    </BODY>
</HTML>