<?php
/**
 * Custom Options Templates
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitoptionstemplate
 * @version      3.2.2
 * @license:     FoqAPsDYiV5k0g2ao7Zx8pPoJiVNkUYZBpxixzEerG
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
/* @var $this Aitoc_Aitsys_Block_Notification */
?>
<div class="fieldset">
  <div class="news">
      <?php foreach ($this->getNews() as $item) { ?>
          <dl class="item">
            <dt>
                <?php if (isset($item['title']) && $item['title']) { ?>
                    <h2><?php echo $item['title']?></h2>
                <?php } ?>
            </dt>
            <dd>
              <?php echo $item['content']?>
            </dd>
          </dl>
      <?php } ?>
  </div>
</div>