editAreaLoader.lang["ja"]={
new_document: "ж–°и¦ЏдЅњж€ђ",
search_button: "ж¤њзґўгѓ»зЅ®жЏ›",
search_command: "ж¬Ўг‚’ж¤њзґў / ж¤њзґўзЄ“г‚’иЎЁз¤є",
search: "ж¤њзґў",
replace: "зЅ®жЏ›",
replace_command: "зЅ®жЏ› / зЅ®жЏ›зЄ“г‚’иЎЁз¤є",
find_next: "ж¬Ўг‚’ж¤њзґў",
replace_all: "е…ЁзЅ®жЏ›",
reg_exp: "ж­Ји¦ЏиЎЁзЏѕ",
match_case: "е¤§ж–‡е­—е°Џж–‡е­—гЃ®еЊєе€Ґ",
not_found: "и¦‹гЃ¤гЃ‹г‚ЉгЃѕгЃ›г‚“гЂ‚",
occurrence_replaced: "зЅ®жЏ›гЃ—гЃѕгЃ—гЃџгЂ‚",
search_field_empty: "ж¤њзґўеЇѕи±Ўж–‡е­—е€—гЃЊз©єгЃ§гЃ™гЂ‚",
restart_search_at_begin: "зµ‚з«ЇгЃ«йЃ”гЃ—гЃѕгЃ—гЃџгЂЃе§‹г‚ЃгЃ«ж€»г‚ЉгЃѕгЃ™",
move_popup: "ж¤њзґўзЄ“г‚’з§»е‹•",
font_size: "--гѓ•г‚©гѓігѓ€г‚µг‚¤г‚є--",
go_to_line: "жЊ‡е®љиЎЊгЃёз§»е‹•",
go_to_line_prompt: "жЊ‡е®љиЎЊгЃёз§»е‹•гЃ—гЃѕгЃ™:",
undo: "е…ѓгЃ«ж€»гЃ™",
redo: "г‚„г‚Љз›ґгЃ—",
change_smooth_selection: "г‚№гѓ гѓјг‚№иЎЁз¤єгЃ®е€‡г‚Љж›їгЃ€пј€CPUг‚’дЅїгЃ„гЃѕгЃ™пј‰",
highlight: "ж§‹ж–‡еј·иЄїиЎЁз¤єгЃ®е€‡г‚Љж›їгЃ€",
reset_highlight: "ж§‹ж–‡еј·иЄїиЎЁз¤єгЃ®гѓЄг‚»гѓѓгѓ€",
help: "гѓгѓ«гѓ—г‚’иЎЁз¤є",
save: "дїќе­",
load: "иЄ­гЃїиѕјгЃї",
line_abbr: "иЎЊ",
char_abbr: "ж–‡е­—",
position: "дЅЌзЅ®",
total: "еђ€иЁ€",
close_popup: "гѓќгѓѓгѓ—г‚ўгѓѓгѓ—г‚’й–‰гЃг‚‹",
shortcuts: "г‚·гѓ§гѓјгѓ€г‚«гѓѓгѓ€",
add_tab: "г‚їгѓ–г‚’жЊїе…ҐгЃ™г‚‹",
remove_tab: "г‚їгѓ–г‚’е‰Љй™¤гЃ™г‚‹",
about_notice: "жіЁж„Џпјљж§‹ж–‡еј·иЄїиЎЁз¤єгЃЇзџ­гЃ„гѓ†г‚­г‚№гѓ€гЃ§гЃ—гЃ‹жњ‰еЉ№гЃ«ж©џиѓЅгЃ—гЃѕгЃ›г‚“гЂ‚",
toggle: "гѓ†г‚­г‚№гѓ€г‚ЁгѓЄг‚ўгЃЁeditAreaгЃ®е€‡г‚Љж›їгЃ€",
accesskey: "г‚ўг‚Їг‚»г‚№г‚­гѓј",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "е‡¦зђ†дё­гЃ§гЃ™...",
fullscreen: "fullscreen",
syntax_selection: "--Syntax--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "Close file"
};
