<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<div class="layer-post layer-gettoknowteampost">
   <div class="layer-titletop">
		<h3><?php echo $this->__('Partially Paid Orders'); ?></h3>
	</div>
	<?php $partialpaymentHelper = Mage::helper('partialpayment/partialpayment');	?>
	<?php if(sizeof($collection)): ?>
		<?php $odd_even = 1; ?>
		<div class="layer-gettoknowteamdesc">
		<script src="<?php echo Mage::getBaseUrl('js') ?>indies/payment.js" type="text/javascript"></script>
		<form action="<?php echo $this->getUrl('partialpayment/index/installments') ?>" method="post" id="multishipping-billing-form">
			<div>
				<div class="box-account box-recent">
			    <p></p>
                <?php echo $this->getPagerHtml(); ?>
                <table id="my-orders-table1" class="data-table">
                   <tr class="first last">
                        <th>Order Id</th>
                        <th>Total Amount</th>
                        <th>Paid Amount</th>
                        <th>Remaining Amount</th>
                        <th>Payment Status</th>
                         <th>Installments</th>
                    </tr>
                    <?php $previousOrderId="";$number="even"; ?>
                    <?php foreach ($collection as $order) 
					{ ?>
                     <?php 
		 				$partialPayment = Mage::getModel('partialpayment/partialpayment')->load($order['partial_payment_id']);
						if ($previousOrderId != $order['partial_payment_id'])
						{
							if($number == "even")
								$number = "odd";
							else 
								$number = "even";
						}
	 				?>
                        <tr class="<?php echo $number ?>">
                         
                          <td><?php echo $partialPayment->getOrderId(); ?></td>
                   		  
                         <td class="amount"><?php echo $this->helper('checkout')->formatPrice($partialPayment->getTotalAmount()); ?></td>
                          <td class="amount"><?php echo $this->helper('checkout')->formatPrice($partialPayment->getPaidAmount()); ?></td>
                          <td class="amount"><?php echo $this->helper('checkout')->formatPrice($partialPayment->getRemainingAmount()); ?></td>				
                          <td class="grid-field-center"> <?php echo $partialPayment->getPartialPaymentStatus();?> </td>
                          <td><?php echo $partialPayment->getTotalInstallment();  ?> &nbsp;&nbsp;
						   <a href="<?php echo $this->getUrl('partialpayment/index/installments',array('order_id'=>  $partialPayment->getOrderId(),'partial_payment_id'=>$order['partial_payment_id']))?>">View</a>
                             <?php if($partialPayment->getRemainingAmount() != 0): ?>
                              <?php echo "&nbsp;&nbsp;&nbsp;" . "|" . "&nbsp;&nbsp;&nbsp;"  ?>
						      <a href="<?php echo $this->getUrl('partialpayment/index/installments',array('order_id'=>  $partialPayment->getOrderId(),'partial_payment_id'=>$order['partial_payment_id']))?>">Pay</a>
                          	 <?php endif; ?>
                          </td>
						</tr>
                            <?php  
                                    $odd_even++;
									$previousOrderId = $order['partial_payment_id'];
                      }
                            ?>
			    </table>
                <?php echo $this->getPagerHtml(); ?>
               <p></p>
               </div>
			</div>		
	  </form>
      </div>
    <?php else: ?>
		<div class="layer-gettoknowteamdesc">
            <div>
                <div class="box-account box-recent">
                   	<?php echo $this->__('You have not any partially paid order available.'); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <script type="text/javascript">decorateTable('my-orders-table');</script>
</div>	