<?php
	$partialpaymentAuthentication = Mage::helper('partialpayment/data');
	$partialpaymentHelper = Mage::helper('partialpayment/partialpayment');
	$partialpaymentCalculationHelper = Mage::helper('partialpayment/calculation');

	$validCustomer = $partialpaymentHelper->isValidCustomer();

	if ($partialpaymentAuthentication->canRun() && $partialpaymentHelper->isEnabled()) {
		if ($partialpaymentHelper->isApplyToWholeCart()) {
			$quote = $partialpaymentCalculationHelper->getQuote();
			$subTotal = $partialpaymentCalculationHelper->getBaseSubtotal($quote);

			if ($validCustomer) {
				if ($partialpaymentHelper->isProductPriceValid($subTotal) && $partialpaymentHelper->validateWithMinimumOrderAmount($subTotal)) {
?>
					<script language="javascript">
                        jQuery(window).load(function() {
    <?php
                            $jquery = Mage::getSingleton('core/session')->getJquery();
                            if ($jquery) {
    ?>
                                jQuery("#wholecart_partialpayment_form").modal({
                                    closeHTML:'<a href="#" title="Close" class="modal-close close_wholecart_partialpayment_form"><img src="<?php echo $this->getSkinUrl('partialpayment/images/close.png'); ?>" /></a>',
                                    position:['35%',],
                                    overlayId:'partialpayment-wholecart-overlay',
                                    containerId:'partialpayment-wholecart-container',
                                });
    <?php
                                Mage::getSingleton('core/session')->unsJquery(); 
                            }
    
                            $showWholecartPartialpaymentForm = 0;
                            if ($partialpaymentHelper->isPartialPaymentOptionFlexyPayments()) {
                                $showWholecartPartialpaymentForm = 1;
                            }
                            elseif ($partialpaymentHelper->isPartialPaymentOptional()) {
                                $showWholecartPartialpaymentForm = 1;
                            }
    
                            if ($showWholecartPartialpaymentForm) {
    ?>
                                jQuery('#wholecart-partialpayment-link').click(function (e) {
                                    jQuery('#wholecart_partialpayment_form').modal({
                                        closeHTML:'<a href="#" title="Close" class="modal-close close_wholecart_partialpayment_form"><img src="<?php echo $this->getSkinUrl('partialpayment/images/close.png'); ?>" /></a>',
                                        position:['35%',],
                                        overlayId:'partialpayment-wholecart-overlay',
                                        containerId:'partialpayment-wholecart-container',
                                    });
                                });
    <?php
                            }
    ?>
                        });
                    </script>
    <?php
                    echo '<div class="clearer"></div>';
                    echo '<div class="allow_partial_payment">';
                    echo '<h2>';
                    echo '<em>* </em>';
                    echo '<a href="#" onclick="return false;" onmouseover="showPartialPaymentHelp();" onmouseout="hidePartialPaymentHelp();" style="color:#0A263C;">';
                    echo $this->__('This order is available on ') .$partialpaymentHelper->getFrontendLabel();
                    echo '<img alt="Help" class="partialpayment-help" height="15px;" src="' . $this->getSkinUrl('partialpayment/images/help.jpg') . '" title="Help" width="16px;" />';
                    echo '</a>';
                    if ($showWholecartPartialpaymentForm) {
                        echo '<a href="#" id="wholecart-partialpayment-link" onclick="return false;">' . $this->__('Change') . '</a>';
                    }
                    echo '</h2>';
                    echo '</div>';
                    echo '<div class="clearer"></div>';
    
                    echo '<div id="partialpayment-help">';
                    $surcharge_value = 0;
                    $remaining_installments = 1;
                    $remaining_balance = 0;
                    $tempSubTotal = $subTotal;
    
                    if ($partialpaymentHelper->isPartialPaymentOption2Installments() || $partialpaymentHelper->isPartialPaymentOptionFixedInstallments()) {
                        if ($partialpaymentHelper->isPartialPaymentOptionFixedInstallments()) {
                            $remaining_installments = $partialpaymentHelper->getTotalNoOfInstallment() - 1;
                        }
    
                        if ($partialpaymentHelper->isSurchargeOptionsSingleSurcharge()) {
                            $surcharge_value = $partialpaymentHelper->getSingleSurchargeValue();								
                        }
                        elseif ($partialpaymentHelper->isSurchargeOptionsMultipleSurcharge()) {
                            $surcharge_value = explode(',', $partialpaymentHelper->getMultipleSurchargeValues());
                            $surcharge_value = $surcharge_value[$remaining_installments];
                        }
    
                        if ($partialpaymentHelper->isSurchargeOptionsSingleSurcharge() || $partialpaymentHelper->isSurchargeOptionsMultipleSurcharge()) {
                            if ($partialpaymentHelper->isInstallmentCalculationTypeFixed()) {
                                $tempSubTotal += $surcharge_value;
                            }
                            else {
                                $tempSubTotal += (($tempSubTotal * $surcharge_value) / 100);
                            }
                        }
    
                        $initial_deposit = 0;
    
                        if ($partialpaymentHelper->isInstallmentCalculationTypeFixed()) {
                            $initial_deposit = $partialpaymentHelper->getFirstInstallmentAmount();
                        }
                        else {
                            $initial_deposit = ($tempSubTotal * $partialpaymentHelper->getFirstInstallmentAmount()) / 100;
                        }
    
                        echo 'Initial deposit of ' . Mage::helper('core')->currency($initial_deposit, true, false) . '.';
    
                        $remaining_balance = $tempSubTotal - $initial_deposit;
                    }
    
                    $payment_plan = '';
                    if ($partialpaymentHelper->isPaymentPlanDays()) {
                        $payment_plan = $partialpaymentHelper->getPaymentPlanTotalNoOfDays() . ' days';
                    }
                    elseif ($partialpaymentHelper->isPaymentPlanWeekly()) {
                        $payment_plan = 'week';
                    }
                    else {
                        $payment_plan = 'month';
                    }
    
                    if ($partialpaymentHelper->isPartialPaymentOption2Installments() || $partialpaymentHelper->isPartialPaymentOptionFixedInstallments()) {
                        if ($remaining_installments == 1) {
                            echo '<br />Remaining balance in ' . $remaining_installments . ' installment of ' . Mage::helper('core')->currency($remaining_balance / $remaining_installments, true, false) . ' to be paid in ' . $payment_plan . '.';
                        }
                        else {
                            echo '<br />Remaining balance in ' . $remaining_installments . ' installments of ' . Mage::helper('core')->currency($remaining_balance / $remaining_installments, true, false) . ' to be paid every ' . $payment_plan . '.';
                        }
                    }
                    else {
                        echo 'Installments to be paid every ' . $payment_plan . '.';
                    }
    
                    if ($partialpaymentHelper->isCaptureInstallmentsAutomatically()) {
                        echo '<br />Your CC will be charged automatic.';
                        echo "<br />We don't save your CC details. You are secure.";
                    }
    
                    if ($partialpaymentHelper->isPartialPaymentOption2Installments() || $partialpaymentHelper->isPartialPaymentOptionFixedInstallments()) {
                        echo '<div class="total-to-be-paid">Total to be paid = ' . Mage::helper('core')->currency($tempSubTotal, true, false) . '</div>';
                    }
                    else {
                        echo '<br /><br />';
                    }
    
                    echo '* Final amount varies depending on shipping, tax & other charges.';
    
                    if ($surcharge_value) {
                        echo '<br />* ';
                        if ($partialpaymentHelper->isInstallmentCalculationTypeFixed()) {
                            echo '<span id="surcharge_value">' . Mage::helper('core')->currency($surcharge_value, true, false) . '</span>';
                        }
                        else {
                            echo '<span id="surcharge_value">' . $surcharge_value . '</span>%';
                        }
                        echo ' surcharge applies to all amount.';
                    }
                    echo '</div>';
    
                    if ($showWholecartPartialpaymentForm) {
                        echo '<form action="' . $this->getUrl('checkout/cart/index') . '" id="wholecart_partialpayment_form" method="post" name="wholecart_partialpayment_form">';
                        echo '<div class="allow_partial_payment">';
                        echo '<h2>';
                        echo '<em>* </em>';
                        echo $this->__('This order is available on ') . $partialpaymentHelper->getFrontendLabel() . $this->__(' : ');
                        echo '<select class="required-entry" id="allow_partial_payment" name="allow_partial_payment" onchange="document.getElementById(\'wholecart_partialpayment_form\').submit();">';
    
                        if ($partialpaymentHelper->isPartialPaymentOptionFlexyPayments()) {
                            echo '<option selected="selected" value="0">' . $this->__('Full Payment of ') . Mage::helper('core')->currency($subTotal, true, false) . '</option>';
    
                            for ($i=2;$i<=$partialpaymentHelper->getTotalNoOfInstallment();$i++) {
                                $installment_price = $subTotal;
                                $surcharge_value = 0;
        
                                if ($partialpaymentHelper->isSurchargeOptionsSingleSurcharge()) {
                                    $surcharge_value = $partialpaymentHelper->getSingleSurchargeValue();								
                                }
                                elseif ($partialpaymentHelper->isSurchargeOptionsMultipleSurcharge()) {
                                    $surcharge_value = explode(',', $partialpaymentHelper->getMultipleSurchargeValues());
                                    $surcharge_value = $surcharge_value[$i-1];
                                }
        
                                if ($partialpaymentHelper->isSurchargeOptionsSingleSurcharge() || $partialpaymentHelper->isSurchargeOptionsMultipleSurcharge()) {
                                    if ($partialpaymentHelper->isInstallmentCalculationTypeFixed()) {
                                        $installment_price += $surcharge_value;
                                    }
                                    else {
                                        $installment_price += (($installment_price * $surcharge_value) / 100);
                                    }
                                }
        
                                echo '<option' . (Mage::getSingleton('core/session')->getPP() == $i?' selected="selected"':'') . ' value="' . $i . '">' . $i . $this->__(' Installments of ') . Mage::helper('core')->currency($installment_price / $i, true, false) . '</option>';
                            }
                        }
                        elseif ($partialpaymentHelper->isPartialPaymentOptional()) {
                            echo '<option selected="selected" value="0">' . $this->__('Full Payment') . '</option>';
                            echo '<option' . (Mage::getSingleton('core/session')->getPP() == 1?' selected="selected"':'') . ' value="1">' . $this->__('Installment') . '</option>';
                        }
    
                        echo '</select>';
                        echo '</h2>';
                        echo '</div>';
                        echo '</form>';
                    }
    ?>
                    <script type="text/javascript" language="javascript">
                        function showPartialPaymentHelp () {
                            document.getElementById('partialpayment-help').style.display = 'block';
                        }
                        
                        function hidePartialPaymentHelp () {
                            document.getElementById('partialpayment-help').style.display = 'none';
                        }
                    </script>
<?php
				}
			}
			elseif($partialpaymentHelper->displayPartialPaymentMessage())
			{ 
?>
				<div class="customer_group_message">
					<?php echo $this->__('Please login to know your parital payment facility.'); ?>
                </div>
<?php
	       }
		}
	}
?>