<?php
/**
 * Product:     Custom Product Preview
 * Package:     Aitoc_Aitcg_3.0.1_1.0.0_520274
 * Purchase ID: 9XHJkpl9USQGlgqMmhzeUoZOIR22A95V3tio9yYTqY
 * Generated:   2013-03-05 20:52:02
 * File path:   app/design/frontend/default/default/template/aitcg/view/options/type/cgfile.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php $_option = $this->getOption(); ?>
<?php $_fileInfo = $this->getFileInfo(); ?>
<?php $_image = $this->getImage(); ?>
<?php $_rand = rand(); ?>
<?php $_fileOption = 'options_' . $_option->getId(); ?>
<?php $_defaultValues = ($this->getProduct()->hasPreconfiguredValues()?$this->getProduct()->getPreconfiguredValues()->getData('options/' . $this->getOption()->getId()):array('img_data'=>'')); ?>
<?php $checkboxEnabled = Mage::getStoreConfig('catalog/aitcg/aitcg_confirm_checkbox'); ?>
<?php if($checkboxEnabled): ?>
    <?php $fullCheckboxEnabled = Mage::getStoreConfig('catalog/aitcg/aitcg_confirm_fullcheckbox'); ?>
<?php endif; ?>
<?php $sharedImgId = Mage::helper('aitcg')->getSharedImgId($_rand) ?>
<?php $sharedImgUrl = Mage::helper('aitcg')->getSharedImgUrl($sharedImgId) ?>

<script type="text/javascript">
//<![CDATA[

AitPopupHtml = '<div id="loading-mask" style="display:none">'+
            '<p class="loader" id="loading_mask_loader">'+
                '<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>'+
            '</p></div>';


<?php if($this->getAllowPredefinedColors()): ?>
    var aitcgColorset<?php echo $_rand ?> = new aitcgColorSet({
        source: '<?php echo $this->getColorset()->getValue();?>',
        containerId: 'aitcg_colorset_container<?php echo $_rand ?>',
        initVarName: 'aitcgColorset<?php echo $_rand ?>',
        id: '<?php echo $_rand ?>',
        colorInputId:'colorfield<?php echo $_rand ?>'
    });
<?php endif; ?>

cimage<?php echo $_rand; ?> = Class.create(<?php echo Mage::helper('aitcg')->getAitcgMainJsClass() ?>,  
{     
        <?php if($_image !== false): ?>
        optionIsRequired: '<?php echo $_option->getIsRequire(); ?>',
        productImageThumbnailUrl: '<?php echo $_image["thumbnail_url"]; ?>',
        productImageFullUrl: '<?php echo $_image["full_image"]; ?>',
        productImageSizeX: <?php echo $_image["default_size"][0]; ?>,
        productImageSizeY: <?php echo $_image["default_size"][1]; ?>,
        productImageThubnailSizeX: <?php echo $_image["thumbnail_size"][0]; ?>,
        productImageThubnailSizeY: <?php echo $_image["thumbnail_size"][1]; ?>,
        areaSizeX: <?php echo $_option->getAreaSizeX() ?>,
        areaSizeY: <?php echo $_option->getAreaSizeY() ?>,
        areaOffsetX: <?php echo $_option->getAreaOffsetX() ?>,
        areaOffsetY: <?php echo $_option->getAreaOffsetY() ?>,
        editorEnabled: true,
        useUserImage : <?php echo (int)$_option->getUseUserImage() ?>,
        useText : <?php echo (int)$_option->getUseText() ?>,
        usePredefinedImage : <?php echo (int)$_option->getUsePredefinedImage() ?>,
        predefinedOptions: <?php echo Mage::helper('aitcg/category')->getPredefinedCatsOptionHtml($_option->getPredefinedCats()); ?>'',
        fontOptions: '<?php echo Mage::helper('aitcg/font')->getFontOptionHtml(); ?>',
        fontPreviewUrl: '<?php echo Mage::getUrl('aitcg/ajax/fontPreview')?>',        
        categoryPreviewUrl: '<?php echo Mage::getUrl('aitcg/ajax/categoryPreview')?>',        
        jsUrl: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>',  
         <?php else: ?>
        editorEnabled: false,
        <?php endif; ?>
        rand: '<?php echo $_rand; ?>',
        checkboxEnabled:'<?php echo $checkboxEnabled; ?>',
        text: {
            close: "<?php echo $this->__('Close'); ?>",
            apply: "<?php echo $this->__('Apply') ?>",
            reset: "<?php echo $this->__('Reset'); ?>",
            required: "<?php echo $this->__('This is a required field.'); ?>",
            texttoadd: "<?php echo $this->__('Text to add...'); ?>",
            addtext: "<?php echo $this->__('Add text'); ?>",
            pickcolor: "<?php echo $this->__('Pick color'); ?>",
            addimage: "<?php echo $this->__('Add image'); ?>",
            user_title: "<?php echo $this->__('2. Add Your Own Logo'); ?>",
            predefined_title: "<?php echo $this->__('1. Choose Color and Predefined Logo'); ?>",
            text_title: "<?php echo $this->__('3. Add Number'); ?>",            
            svg: "<?php echo $this->__('Save as SVG'); ?>",
            png: "<?php echo $this->__('Convert to PNG'); ?>",
            scale: "<?php echo $this->__('Scale'); ?>"
            <?php if ($checkboxEnabled && $fullCheckboxEnabled): ?>,
            confirm: "<?php echo Mage::getStoreConfig('catalog/aitcg/aitcg_confirm_fulltext'); ?>",
            agree: "<?php echo $this->__('Agree'); ?>",
            disagree: "<?php echo $this->__('Disagree'); ?>"
            <?php endif; ?>
        },
        product_id: '<?php echo $_option->getProductId(); ?>',
        addImageUrl: '<?php echo Mage::getUrl('aitcg/ajax/addImage'); ?>',
        addTextUrl: '<?php echo Mage::getUrl('aitcg/ajax/addText'); ?>',
        addPredefinedUrl: '<?php echo Mage::getUrl('aitcg/ajax/addPredefined'); ?>',        
        saveSvgUrl: '<?php echo Mage::getUrl('aitcg/index/svg'); ?>',
        optionId : <?php echo $_option->getId() ?>,
        textLength : <?php echo (int)$_option->getTextLength() ?>,
        allowColorpick : <?php echo (int)$_option->getAllowColorpick() ?>,
        allowOnlyPredefColor: <?php echo (int)$this->getAllowPredefinedColors()?>,
        textImgAspectRatio: '<?php echo $this->getTextObjAspectRatio()?>',
        editorHelp: "<?php echo $this->__('Once you select your image, click Add Image to add it to the product. Next move around or resize the image to suit your desired end state. If you would like to add multiple images or text, you can select another image or text and click add to image.'); ?>", 
        buttonHelp: "<?php echo $this->__('Save custom image preview to your hard drive (optional)'); ?>", 
        emptyImgUrl : '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'aitoc/aitcg/img/blank.gif' ?>',
        socialWidgetsImgCreatePath : '<?php echo Mage::helper('aitcg')->getImgCreatePath() ?>',
        socialWidgetsReservedImgId : '<?php echo $sharedImgId ?>',
        templateImgPath : '<?php echo $_image['value'] ?>',
        socialWidgetsImgViewUrl : '<?php echo $sharedImgUrl ?>'
        });
opCimage<?php echo $_rand; ?> = new cimage<?php echo $_rand; ?>('<?php echo $_fileOption; ?>');
//]]>
</script>
<dt><label<?php if ($_option->getIsRequire()) : ?> class="required"<?php endif ?>><?php echo  $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getIsRequire()) : ?> <span class="required"><em>*</em></span><?php endif ?></label>
    <?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
  <div>
      <div class="aitcg_error" style="display: none;">
        <?php echo $this->__('Sorry, but your browser does NOT support HTML5 elements and this feature is not working or may work incorrectly.');?><br />
        <span class="error_default" style="display: none"><?php echo $this->__('Please, try using different browser.');?></span>
        <span class="error_android" style="display: none"><?php echo $this->__('Please, try using different browser (Opera Mini for example) or update your Android to a newer version.');?></span>
      </div>
      <?php echo $this->__('Click on the preview to start editing'); ?>
      <div class="aitcg_image_div"  style="float:none;" id="preview_container<?php echo  $_option->getId(); ?>"  onclick="opCimage<?php echo $_rand; ?>.startEditor();"></div>
              <input type="hidden" id="options_<?php echo $_option->getId() ?>" class="input-text<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> product-custom-option" name="options[<?php echo $_option->getId() ?>]" value="<?php echo $this->htmlEscape($_defaultValues['img_data'])?>" />
            <?php if ($checkboxEnabled == 1): ?>
            <p class="no-margin">                
                <input type="checkbox" name="<?php echo $_rand; ?>_checkbox" id="<?php echo $_fileOption; ?>_checkbox" class="product-custom-option <?php if ($_option->getIsRequire()) : ?>required-entry<?php endif ?>" <?php if($fullCheckboxEnabled == 1): ?>onClick="return opCimage<?php echo $_rand; ?>.checkConfirmBox(this);"<?php endif; ?>/>
                <?php if($fullCheckboxEnabled == 1): ?>
                <a href="#" onClick="return opCimage<?php echo $_rand; ?>.checkConfirmBox(this);"><?php echo Mage::getStoreConfig('catalog/aitcg/aitcg_confirm_text'); ?></a>
                <?php else: ?>
                <label for="<?php echo $_fileOption; ?>_checkbox"><?php echo Mage::getStoreConfig('catalog/aitcg/aitcg_confirm_text'); ?></label>
                <?php endif; ?>
            </p>
            <?php endif; ?>  
  </div>
</dd>
<script type="text/javascript">
//<![CDATA[
/*Event.observe(document, 'dom:loaded', function(){*/ opCimage<?php echo $_rand; ?>.preview("preview_container<?php echo  $_option->getId(); ?>");/*});*/
//]]>
</script>
<img class='techimg' style="display:none;">

<?php if(Mage::getStoreConfig('catalog/aitcg/aitcg_use_social_networks_sharing')) : ?>
<div id="socialWidgetsTip<?php echo $_option->getId() ?>" style="display:none;" onclick="opCimage<?php echo $_rand; ?>.createImage();return false;">
<a href="#"><?php echo $this->__('Click to share your customized image'); ?></a></div>
<div id="imgSizeError<?php echo $_option->getId() ?>" style="display:none;">
<?php echo $this->__('You image exceeds maximum allowed size'); echo ' (' . 
Mage::getStoreConfig('catalog/aitcg/aitcg_social_networks_sharing_max_img_width') . 'x' . 
Mage::getStoreConfig('catalog/aitcg/aitcg_social_networks_sharing_max_img_height') . ')';?></div>
<div class="fb-like" style="visibility:hidden;display:inline;vertical-align:top;" id="fbaitcg<?php echo $_option->getId() ?>" data-layout="button_count" data-href="<?php echo $sharedImgUrl ?>" data-send="true" data-show-faces="false"></div>
<div id="gaitcgWrapper<?php echo $_option->getId() ?>" style="display:inline;"> </div>
    <?php if ($this->canEmailToFriend()): ?>
    <?php $emailToFriendUrl = Mage::helper('aitcg')->getEmailToFriendUrl($this->getProduct(), $sharedImgId) ?>
    <div id="emailToFriend<?php echo $_option->getId() ?>" style="display:none;">
    <p style="display:inline;" class="email-friend"><a href="<?php echo $emailToFriendUrl ?>" target="_blank"><img style="widht:107px;height:20px;" src="<?php echo $this->getSkinUrl('aitoc/aitcg/images') . '/email_to_a_friend.gif' ?>" /></a></p>
    </div>
    <?php endif; ?>
<div id="socialButtonsLoader<?php echo $_option->getId() ?>" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Email to a Friend') ?>" /></div>
<?php endif; ?>