<?php
/**
 * Delivery Date
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Deliverydate
 * @version      1.1.7
 * @license:     CGRl40OoIpwl63Yy9HmSwXtQ6ZlFDRlIXEc7HbfxdJ
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
echo $this->getChildHtml('availablecopy') ?>

<ul>
<?php foreach($this->getFields() as $field): ?>
    <li>
        <div class="input-box">
		<?php echo $field->getHtml() ?>
		<div>
	</li>
<?php endforeach?>
</ul>