<?php
/**
 * Product:     Custom Product Preview
 * Package:     Aitoc_Aitcg_3.0.1_1.0.0_520274
 * Purchase ID: 9XHJkpl9USQGlgqMmhzeUoZOIR22A95V3tio9yYTqY
 * Generated:   2013-03-05 20:52:02
 * File path:   app/design/adminhtml/default/default/template/aitcg/catalog/product/edit/options/type/cgfile.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<script type="text/javascript">

OptionTemplateCg = '<input type="hidden" name="validation_{{option_id}}_result" value="" >'+
        '<table class="border" cellpadding="0" cellspacing="0">'+
// first line        
        '<tr class="headings">'+
            '<th class="type-price"><?php echo Mage::helper('catalog')->__('Price') ?></th>'+
            '<th class="type-type"><?php echo Mage::helper('catalog')->__('Price Type') ?></th>'+
            '<th class="type-sku"><?php echo Mage::helper('catalog')->__('SKU') ?></th>'+            
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Enable Customer Image') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Enable Predefined Images') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Categories of Predefined Images') ?></th>'+
            '<th class="last"><?php echo Mage::helper('aitcg')->__('Image Template') ?> <span class="required">*</span><br><?php echo Mage::helper('aitcg')->__('Note: Real image size is displayed at front end for the customer') ?></th>'+
        '</tr>'+
        '<tr>'+
            '<td><input class="input-text type="text" name="product[options][{{option_id}}][price]" value="{{price}}"></td>'+
            '<td><?php echo $this->getPriceTypeSelectHtml() ?></td>'+
            '<td><input type="text" class="input-text" name="product[options][{{option_id}}][sku]" value="{{sku}}"></td>'+
            '<td><input type="hidden" id="aitcg_option_use_user_image_{{option_id}}_tmp" value="{{use_user_image}}">'+
            '<input class="input-text" type="checkbox" name="product[options][{{option_id}}][use_user_image]" id="aitcg_option_use_user_image_{{option_id}}" value="1"></td>'+

            '<td><input type="hidden" id="aitcg_option_use_predefined_image_{{option_id}}_tmp" value="{{use_predefined_image}}">'+
            '<input class="input-text" type="checkbox" name="product[options][{{option_id}}][use_predefined_image]" id="aitcg_option_use_predefined_image_{{option_id}}" value="1"></td>'+
            //$(\'aitcg_option_predefined_cats_{{option_id}}\').value=
            '<td><select class="select" multiple="multiple" onchange="$(\'aitcg_option_predefined_cats_{{option_id}}\').setValue($(this).getValue())" id="aitcg_option_predefined_cats_{{option_id}}_tmp">'+
            <?php echo Mage::helper('aitcg/category')->getPredefinedCatsOptionHtml() ?>
            '</select>'+
            '<input type="hidden" name="product[options][{{option_id}}][predefined_cats]" id="aitcg_option_predefined_cats_{{option_id}}" value="{{predefined_cats}}"></td>'+            
            
            '<td class="type-last last" nowrap>'+
                '<select class="required-option-cgfile-type-template required-option-select select validate-select select-type-cgfile" id="aitcg_option_select_{{option_id}}" name="product[options][{{option_id}}][image_template_id]" onchange="aitcgImageSelector.loadImage(\'{{option_id}}\', this.value, event);">'+
                    '<option value="0"><?php echo Mage::helper('aitcg')->__('Select Image Template') ?></option>'+
                    <?php echo $this->getSelectImageOptions() ?>
                '</select>'+
            '</td>'+
        '</tr>'+
//second line        
        '<tr class="headings">'+       
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Enable Text') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Max Text Length') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Allow Distortion of Text Objects') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Enable Colorpicker') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Allow Only Predefined Colors') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('') ?></th>'+
            '<th class="type-title"><?php echo Mage::helper('aitcg')->__('Predefined Color Set') ?></th>'+
        '</tr>'+
        '<tr>'+
            '<td><input type="hidden" id="aitcg_option_use_text_{{option_id}}_tmp" value="{{use_text}}">'+
            '<input class="input-text" type="checkbox" name="product[options][{{option_id}}][use_text]" id="aitcg_option_use_text_{{option_id}}" value="1"></td>'+

            '<td>'+
            '<input class="input-text" type="text" name="product[options][{{option_id}}][text_length]" id="aitcg_option_text_length_{{option_id}}" value="{{text_length}}"></td>'+
            
            '<td><input type="hidden" id="aitcg_option_allow_text_distortion_{{option_id}}_tmp" value="{{allow_text_distortion}}">'+
            '<?php echo $this->getAllowTextDistortionSelectHtml() ?></td>'+
            
            '<td><input type="hidden" id="aitcg_option_allow_colorpick_{{option_id}}_tmp" value="{{allow_colorpick}}">'+
            '<input class="input-text" type="checkbox" name="product[options][{{option_id}}][allow_colorpick]" id="aitcg_option_allow_colorpick_{{option_id}}" value="1"></td>'+
            
            '<td><input type="hidden" id="aitcg_option_allow_predefined_colors_{{option_id}}_tmp" value="{{allow_predefined_colors}}">'+
            '<?php echo $this->getAllowPredefinedColorsSelectHtml() ?></td>'+
            
            '<td></td>'+
            
            '<td><input type="hidden" id="aitcg_option_color_set_id_{{option_id}}_tmp" value="{{color_set_id}}">'+
            '<?php echo $this->getColorSetSelectHtml() ?></td>'+
        '</tr>'+
//end of lines        
        '<tr>'+
            '<th class="last" colspan="10" id="aitcg_option_select_{{option_id}}_image"></th>'+
        '</tr>'+
    '</table>'+
    '<input type="hidden" id="product_option_{{option_id}}_coords_offset_x" name="product[options][{{option_id}}][area_offset_x]" value="{{area_offset_x}}">'+
    '<input type="hidden" id="product_option_{{option_id}}_coords_offset_y" name="product[options][{{option_id}}][area_offset_y]" value="{{area_offset_y}}">'+
    '<input type="hidden" id="product_option_{{option_id}}_coords_size_x" name="product[options][{{option_id}}][area_size_x]" value="{{area_size_x}}">'+
    '<input type="hidden" id="product_option_{{option_id}}_coords_size_y" name="product[options][{{option_id}}][area_size_y]" value="{{area_size_y}}">';

if ($('option_panel_type_file')) {
    $('option_panel_type_file').remove();
}

PrintableAreaEditor = <?php echo $this->getChildHtml('aitcg_printarea_window'); ?>;

aitcgImageSelectorOpened = Class.create(Aitcg.ImageSelectorOpened,  
{
    customImages : <?php echo $this->getSelectImageIds()->toJson() ?>,
    imageText  : '<div style="position:relative;padding:1px;"><img src="{{thumbnail_url}}" alt="{{frontend_label}}" title="{{frontend_label}}" />' +
    '<div style="position:absolute; top:{{top}}px;left:{{left}}px;width:{{width}}px;height:{{height}}px;border:1px solid black;"></div></div><br />'+
    '<button type="button" class="scalable" onclick="Aitcg.loadAreaEditor({{option_id}});"><span><?php echo Mage::helper('aitcg')->__('Edit Printable Area'); ?></span></button>',
});
aitcgImageSelector = new aitcgImageSelectorOpened();

Validation.addAllThese([
    ['required-option-cgfile-type-template', '<?php echo Mage::helper('aitcg')->__('Please select Image Template.') ?>', function(v, elm) {
        var selectTypesFlag = false;
        if(elm.id && elm.value != 0) {
            selectTypesFlag = true;
        }
        elm.advaiceContainer = elm.id+'_advice';
        return selectTypesFlag;
}]]);

</script>