<?php
/**
 * Product:     Custom Product Preview
 * Package:     Aitoc_Aitcg_3.0.1_1.0.0_520274
 * Purchase ID: 9XHJkpl9USQGlgqMmhzeUoZOIR22A95V3tio9yYTqY
 * Generated:   2013-03-05 20:52:02
 * File path:   app/design/adminhtml/default/default/template/aitcg/system/cache/image_cache_management.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('aitcg')->__('Custom Product Preview Image Management') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('cgadmin/cache/clean');?>" method="POST">
<?php echo $this->getBlockHtml('formkey')?>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button type="submit" class="scalable"><span><?php echo Mage::helper('aitcg')->__('Flush CPP Temporary Images') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('aitcg')->__('Delete all temporary images used in CPP that are older than')?>
            <select name="daysamount">
                <option value='1'>1 Day</option>
                <option value='7'>1 Week</option>
                <option value='30' selected="selected">1 Month</option>
                <option value='90'>3 Months</option>
            </select>
        </td>
    </tr>
</table>
</form>
<?php echo $this->getChildHtml(); ?>