<?php if($this->getSource() instanceof Mage_Sales_Model_Order){ ?>
<?php if ((float) $this->getSource()->getDepositAmountRefunded()): ?>
    <tr>
        <td class="label"><strong><?php echo Mage::helper('deposit')->__('Deposit refunded to customer') ?></strong></td>
        <td><strong><?php echo $this->getSource()->getDepositAmountRefunded(); ?></strong></td>
    </tr>
<?php endif; ?>
<?php } else { ?>
<?php if ((float) $this->getSource()->getDepositAmount()): ?>
    <tr>
        <td class="label"><strong><?php echo Mage::helper('deposit')->__('Deposit Refunded') ?></strong></td>
        <td><strong><?php echo $this->getSource()->getDepositAmount(); ?></strong></td>
    </tr>
<?php endif; 
}?>

