<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getDepositAmount()): ?>
    <tr>
        <?php $partialpaymentHelper = Mage::helper('partialpayment/partialpayment'); ?>
    	<?php if(($this->getSource()->getBaseDepositAmount() > 0) && ($this->getSource()->getBaseFeeAmount() > 0) && ($this->getSource()->getSubtotalInclTax() >= $partialpaymentHelper->getMinimumOrderAmount()) && ($this->getSource()->getSubtotalInclTax() > $this->getSource()->getBaseFeeAmount()) && ($this->getSource()->getGrandTotal() > $this->getSource()->getBaseFeeAmount()) && ($this->getSource()->getBaseDepositAmount() > $this->getSource()->getTaxAmount())): ?>
	        <td class="label">
				<?php echo Mage::helper('deposit')->formatDeposit($this->getSource()->getDepositAmount()); ?>
			</td>
    	    <td>
        	    <?php echo $this->displayPrices($this->getSource()->getBaseDepositAmount(), $this->getSource()->getDepositAmount()); ?>
	        </td>
		<?php endif; ?>
    </tr>
<?php endif; ?>