<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Owner
 * Date: 09.02.12
 * Time: 15:45
 * To change this template use File | Settings | File Templates.
 */
class Infomodus_Upslabel_Adminhtml_Upslabel_Intermediate extends Mage_Adminhtml_Block_Template
{
    public function __construct()
    {
        echo '1111111111111111111111111'; exit;
        parent::__construct();
        $this->setTemplate('upslabel/intermediate.phtml');
    }
}